name: Deploy to Azure App Service

on:
  push:
    branches: [ "main" ]  # or your default branch
  workflow_dispatch:      # allows manual trigger

env:
  AZURE_WEBAPP_NAME: meeting-transcription    # set this to your app's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'              # set this to the path to your web app project
  NODE_VERSION: '20.x'                        # set this to the node version to use
  PYTHON_VERSION: '3.8'                       # set this to the python version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create uploads and transcripts directories
      run: |
        mkdir -p uploads
        mkdir -p transcripts

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 